# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cristina Menghini
email: cmenghin@cs.brown.edu
description: >- # this means to ignore newlines until "baseurl:"
  Ciao visitor, this is Cristina! 👋
  I'm a postdoc in the Computer Science department at Brown University 🇺🇸, where I do fun research in the BATS lab led by Stephen Bach. As data is changing our notion of the world, 
  I contribute to this change by either designing models that learn when only limited amount of labeled data is available, or understanding humans behaviours and interactions with events and products, with a computational approach.  
  
  I landed at Brown as Visiting Ph.D. student in the BigData group, where I worked with Eli Upfal and Matteo Riondato. In July 2021, I defended my Ph.D. in Computer Engineering from Sapienza University 🇮🇹, advised by Aris Anagnostopoulos and Stefano Leonardi.
  I earned my master's degree in Data Science at Sapienza University, after one-year exchange in the School of Computer and Communication Sciences at EPFL 🇨🇭, where I joined Data Science Lab led by Robert West.
  Before that, I got a bachelor degree at Sapienza University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
remote_theme: pages-themes/hacker@v0.2.0
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
